from __future__ import annotations

from pathlib import Path

from .constants import DATA_PACK_SCHEMA_VERSION


def _prompt_path(name: str) -> Path:
    # backend/council/prompts.py -> backend/
    return Path(__file__).resolve().parents[1] / "prompts" / name


def _load_prompt(name: str) -> str:
    path = _prompt_path(name)
    return path.read_text(encoding="utf-8")


def _workflow_context_block(*, stage_num: int, stage_name: str) -> str:
    extra = ""
    if stage_num == 1:
        extra = (
            "- Stage 1 must be grounded in the full report. If a PDF is >10 pages, ingestion may occur in multiple\n"
            "  multimodal passes before writing the final narrative.\n"
        )
    elif stage_num == 2:
        extra = (
            "- Stage 2 peer review must be evidence-based: evaluate each analysis against the ORIGINAL report text\n"
            "  and (when provided) the DATA PACK extracted from ALL pages.\n"
        )
    elif stage_num == 3:
        extra = (
            "- Stage 3 revision must incorporate peer review feedback while remaining faithful to the ORIGINAL report\n"
            "  text and (when provided) the DATA PACK.\n"
        )
    elif stage_num == 4:
        extra = (
            "- Stage 4 consolidation must synthesize revised analyses while keeping numeric claims aligned with the\n"
            "  ORIGINAL report text and (when provided) the DATA PACK.\n"
        )
    elif stage_num == 5:
        extra = (
            "- Stage 5 final review must vote REVISE if required tables/sections are missing or if numeric claims do\n"
            "  not match the ORIGINAL report text / DATA PACK.\n"
        )
    elif stage_num == 6:
        extra = (
            "- Stage 6 final draft must apply required changes and keep all numeric claims aligned with the ORIGINAL\n"
            "  report text / DATA PACK.\n"
        )

    return (
        "WORKFLOW CONTEXT (read carefully):\n"
        f"- You are working in Stage {stage_num}: {stage_name}.\n"
        "- A structured DATA PACK may be provided below. It is generated by processing ALL PDF pages, "
        "including graphics/tables, using multi-pass vision when needed.\n"
        "- A MULTIMODAL VISION TRANSCRIPT may also be provided. Use it to capture image-only tables/figures that OCR\n"
        "  may miss; do not claim data is missing when it is present there.\n"
        "- Treat the DATA PACK as authoritative for transcribed numeric values; do not claim data is missing "
        "when it is present in the DATA PACK or the report text.\n"
        "- Do not invent numbers. If a value is shown as N/A, report it as present but N/A.\n"
        f"{extra}"
    )


def _data_pack_prompt(*, pages: list[int], focus: str) -> str:
    pages_str = ", ".join(str(p) for p in pages) if pages else "(unknown)"
    return (
        "You are performing STRICT DATA TRANSCRIPTION from qEEG report page images.\n"
        "Return JSON ONLY (no markdown, no prose).\n\n"
        f"Pages provided in this call: {pages_str}\n"
        f"Extraction focus: {focus}\n\n"
        "Canonical identifiers (use EXACT strings):\n"
        "- performance_metric.metric: physical_reaction_time | trail_making_test_a | trail_making_test_b\n"
        "- evoked_potential.metric: audio_p300_delay | audio_p300_voltage\n"
        "- state_metric.metric: cz_theta_beta_ratio_ec | f3_f4_alpha_ratio_ec\n"
        "- peak_frequency.metric: frontal_peak_frequency_ec | central_parietal_peak_frequency_ec | occipital_peak_frequency_ec\n"
        "- p300_cp_site.site: C3 | CZ | C4 | P3 | PZ | P4\n"
        "- n100_central_frontal_average.fact_type: n100_central_frontal_average\n\n"
        "JSON schema:\n"
        "{\n"
        f'  \"schema_version\": {DATA_PACK_SCHEMA_VERSION},\n'
        "  \"pages_seen\": [1, 2],\n"
        "  \"page_inventory\": [\n"
        "    {\"page\": 1, \"title\": \"...\", \"contains\": [\"summary_table\"], \"notes\": \"...\"}\n"
        "  ],\n"
        "  \"facts\": [\n"
        "    {\n"
        "      \"fact_type\": \"performance_metric\",\n"
        "      \"metric\": \"physical_reaction_time\",\n"
        "      \"session_index\": 1,\n"
        "      \"value\": 283,\n"
        "      \"unit\": \"ms\",\n"
        "      \"sd_plus_minus\": 38,\n"
        "      \"target_range\": \"255-367 ms\",\n"
        "      \"shown_as\": null,\n"
        "      \"source_page\": 1\n"
        "    },\n"
        "    {\n"
        "      \"fact_type\": \"performance_metric\",\n"
        "      \"metric\": \"trail_making_test_a\",\n"
        "      \"session_index\": 1,\n"
        "      \"value\": 56,\n"
        "      \"unit\": \"sec\",\n"
        "      \"target_range\": \"37-63 sec\",\n"
        "      \"shown_as\": null,\n"
        "      \"source_page\": 1\n"
        "    },\n"
        "    {\n"
        "      \"fact_type\": \"evoked_potential\",\n"
        "      \"metric\": \"audio_p300_delay\",\n"
        "      \"session_index\": 1,\n"
        "      \"value\": 304,\n"
        "      \"unit\": \"ms\",\n"
        "      \"target_range\": \"247-321 ms\",\n"
        "      \"shown_as\": null,\n"
        "      \"source_page\": 1\n"
        "    },\n"
        "    {\n"
        "      \"fact_type\": \"state_metric\",\n"
        "      \"metric\": \"cz_theta_beta_ratio_ec\",\n"
        "      \"session_index\": 1,\n"
        "      \"value\": 3.1,\n"
        "      \"unit\": \"ratio\",\n"
        "      \"target_range\": \"0.9-2.3\",\n"
        "      \"shown_as\": null,\n"
        "      \"source_page\": 1\n"
        "    },\n"
        "    {\n"
        "      \"fact_type\": \"peak_frequency\",\n"
        "      \"metric\": \"frontal_peak_frequency_ec\",\n"
        "      \"session_index\": 1,\n"
        "      \"value\": 8.5,\n"
        "      \"unit\": \"Hz\",\n"
        "      \"target_range\": \"9.0-11.0 Hz\",\n"
        "      \"shown_as\": null,\n"
        "      \"source_page\": 1\n"
        "    },\n"
        "    {\n"
        "      \"fact_type\": \"p300_cp_site\",\n"
        "      \"site\": \"C3\",\n"
        "      \"session_index\": 1,\n"
        "      \"yield\": 38,\n"
        "      \"uv\": 11.9,\n"
        "      \"ms\": 308,\n"
        "      \"shown_as\": null,\n"
        "      \"source_page\": 2\n"
        "    },\n"
        "    {\n"
        "      \"fact_type\": \"n100_central_frontal_average\",\n"
        "      \"session_index\": 1,\n"
        "      \"yield\": 36,\n"
        "      \"uv\": -4.4,\n"
        "      \"ms\": 120,\n"
        "      \"shown_as\": null,\n"
        "      \"source_page\": 2\n"
        "    }\n"
        "  ],\n"
        "  \"unparsed_required\": [\n"
        "    {\"field\": \"p300_cp_site\", \"page\": 2, \"reason\": \"...\"}\n"
        "  ]\n"
        "}\n\n"
        "Rules:\n"
        "- Transcribe only what you can read confidently from the images. Do not infer or normalize.\n"
        "- Use JSON numbers (not strings) whenever possible.\n"
        "- If the report shows N/A, set the numeric field to null and set \"shown_as\" to \"N/A\".\n"
        "- Always include \"source_page\" for each fact.\n"
        "- Maintain session_index mapping exactly as shown in the legend (Session 1/2/3 color key).\n"
        "- When Peak Frequency is shown, extract it for Frontal, Central-Parietal, and Occipital for every session.\n"
        "- Critical: When the page includes P300 Rare Comparison, extract central-parietal per-site values for "
        "C3, CZ, C4, P3, PZ, P4 for EVERY session shown. Capture yield (#), uv (µV), and ms.\n"
        "- Also extract CENTRAL-FRONTAL AVERAGE N100 values (yield, µV, ms) if present on the page.\n"
        "- Ignore large coherence matrices unless they contain the required facts above.\n"
    )

